# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = '${EDITOR:=vim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
image = [
	{ run = 'feh --geometry 1920x1080 --scale-down --image-bg black --action1 "trashy %F" --action2 "savefeh %F" --action3 "trashy restore %F" -- "$@"', desc = "Image viewer", for = "linux" },
]
open = [
	{ run = 'xdg-open "$@"',                desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$0")"',            desc = "Reveal", for = "linux" },
]
extract = [
	{ run = 'unar "$1"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*",          use = [ "edit" ] },
	{ mime = "image/*",         use = [ "image" ] },
	{ mime = "{audio,video}/*", use = [ "play" ] },
	{ mime = "inode/x-empty",   use = [ "edit", "reveal" ] },

	{ mime = "application/{,g}zip", use = [ "extract", "reveal" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[log]
enabled = false
